Login page
IchabodCrow/myFavouriteFilms pull request #2
Opened 2020-09-01 16:33 UTC by IchabodCrow

2020-09-02 12:42 UTC, reshetov commented on src/App.js
> +        <Route exact path={"/movie"} component={Main}/>
I can open this route without login. It's bad. Try to use PrivateRoute instead - https://medium.com/@tomlarge/private-routes-with-react-router-dom-28e9f40c7146

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +    <div className="flex justify-center mr-8">
Install prettier (https://prettier.io/) in your editor and use it

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +import { reduxForm, Field, SubmissionError } from "redux-form";
Please use Final-form instead Redux-form (https://final-form.org/react)

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +const LoginForm = (props) => {
Split with MEGA-file to separated components

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +              Email
Use locales for text - https://github.com/i18next/react-i18next

2020-09-02 12:42 UTC, reshetov commented on src/utils/validatorsFields.js
> +export const email = value =>
Rename to `emailRegex`

2020-09-02 12:42 UTC, reshetov commented on src/utils/validatorsFields.js
> +  'Не корректный email' : undefined
Locale

2020-09-02 12:42 UTC, reshetov commented on tailwind.js
> +module.exports = {
Remove this file. It's redundant

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +const Login = () => {
Move to component

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +  const registerdUser = JSON.parse(localStorage.getItem("user"));
Typo. `registered`

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +  const registerdUser = JSON.parse(localStorage.getItem("user"));
What you will do if you have more that one user in DB? Perhaps be better to implement `checkUserCredentials` method in some service which will accepts login/password args and checks that they have in DB (LS) and valid?

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
WAT?

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +          email: "Упс. Где-то ошибка",
Just display error label near login form

2020-09-02 12:42 UTC, reshetov commented on src/components/Login/LoginForm.jsx
> +          My favorite cinema
locale

2020-09-02 12:42 UTC, reshetov commented on src/components/UI/Input.js
> +  meta: { touched, error, warning },
Where are you get this? This code doesn't used

2020-09-02 12:42 UTC, reshetov commented on src/containers/LoginContainers.js
> +import { connect } from 'react-redux'
What does it do?

2020-09-02 12:42 UTC, reshetov commented on src/services/insteadServer.js
> +    const user = { email : "fof@fof.ru", password: "123"}
Add more that one user

2020-09-02 12:42 UTC, reshetov commented on src/store/store.js
> +const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
Why is it?

2020-09-07 11:42 UTC, IchabodCrow commented on src/store/store.js
> +const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
To use Redux dev tools in a browser

2020-09-08 14:04 UTC, k41n requested changes
Ok, let's fix more, please have a look at my comments

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +                  <Trans i18nKey="description.signIn">
Why not just `{t('description.signIn')}`? Why do we need `<Trans>`?

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +              type="text"
For email input there is pretty good `email` type

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +            <div className="md:flex md:items-center">
All this looks like pretty good `<Actions>` component we probably will be able to reuse in other form, won't we?

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +            <FieldWithLabel
Looks like `<EmailField name="email" namespace="description" required>`

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +            <FieldWithLabel
Looks like `<PasswordField name="password" namespace="description" required />`

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginPage.jsx
> +          <Trans i18nKey="title">
Why `<Trans />`? We can get `t` with `useTranslation` and use it

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginPage.jsx
> +        <h1 className="font-bold text-4xl bg-purple-500 text-center text-white font-bold py-2 px-4 rounded ">
Looks like we can extract that to `<PageHeader title="title" />` component

2020-09-08 14:04 UTC, k41n commented on src/components/Login/LoginPage.jsx
> +import checkUserCredentails from "../../services/checkUserCredentails";
Unused?

2020-09-08 14:04 UTC, k41n commented on src/components/UI/FieldWithLabel.jsx
> +import { useTranslation } from 'react-i18next'
Unused?

2020-09-08 14:04 UTC, k41n commented on src/components/UI/FieldWithLabel.jsx
> +        <Field
Ok, maybe specify subscription? Are we using all the fields of the FieldState? Are we going to rerender on every change? Subscribe only to what really matters.

2020-09-08 14:04 UTC, k41n commented on src/components/UI/FieldWithLabel.jsx
> +              {meta.error && meta.touched && (
Hide error if field is `modifiedSinceLastSubmit` - so when user starts to fix, error is hidden

2020-09-08 14:04 UTC, k41n commented on src/App.js
> +      <button onClick={ () => changeLanguage('ru') }>Русский</button>
Вёрстка этого куска просто божественна
![image](https://user-images.githubusercontent.com/895649/92486297-96a60b80-f1f4-11ea-9c90-e39be6ad63f5.png)

2020-09-08 14:04 UTC, k41n commented on src/index.js
> +import store from "./store/store"
А зачем тут вообще нужен Redux?

2020-09-08 14:04 UTC, k41n commented on src/services/checkUserCredentails.js
> +  this.checkUserRegistred = (value) => {
Typo

2020-09-08 14:04 UTC, k41n commented on src/services/checkUserCredentails.js
> +const checkUserCredentails = new CheckUserCredentails();
Зачем тут класс вообще? Почему бы не экспортировать просто функцию?

2020-09-08 14:04 UTC, k41n commented on src/services/insteadServer.js
> +const insteadServer = new InsteadServer();
Зачем тут класс? Почему бы просто не экспортировать две функции?

2020-09-08 14:04 UTC, k41n commented on src/store/store.js
> +const store = createStore(reducers, composeEnhancers(applyMiddleware(...middelewares)));
Зачем тут вообще нужен Redux?

2020-09-10 06:56 UTC, k41n requested changes
Almost ideal, some tiny glitches

2020-09-10 06:56 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +            <EmailField
We can do even better:
1) translation namespace can be specified only once. `EmailField` component can do `${namespace}.${name}Placeholder` and `${namespace}.${name}` itself.
2) Email validation always applied to the EmailField so component can do that inside

So real props list is:
- namespace
- name
- required (boolean)

2020-09-10 06:56 UTC, k41n commented on src/components/Login/LoginForm.jsx
> +              validate={composeValidators(required)}
Component can do that itself, just tell it if it is required. So you don't have to import `composeValidators` and `required` in parent form. It's not its business.

2020-09-10 08:49 UTC, k41n approved these changes
👍

2020-09-10 12:47 UTC, merged